# Configuration file for ZERO ERR drive
vendor_id: 0x00000130
product_id: 0x01300060
assign_activate: 0x0000  # DC Synch register
# dc_sync0_shift: 50000 #ns
# dc_mode: true
# sync0_cycle_time: 2000000 #10ms

# watchdog_timer: true
# watchdog_timeout: 100000000  
# auto_enable_set: true
auto_fault_reset: true
auto_state_transitions: true

      
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
